### ISSUE TITLE
btn-default style no longer exists in bootstrap 4.2.1

### ISSUE THREAD

**Issue by jarodhanko** [GedMarc/bootstrap4-dialog#10]
Since btn-default no longer exists as a style (at least it doesn't show a button ...), the button shows up as text only.

Line 907 of bootstrap-dialog.js

Fix: add custom css or change to btn-secondary, btn-dark etc

**Comment by GedMarc** [comment]
Thank you!

Please can you verify the result? :)

**Comment by jarodhanko** [comment]
Looks good!
