### ISSUE TITLE
Compatibility with Bootstrap 4.3.*

### ISSUE THREAD

**Issue by Oviglo** [GedMarc/bootstrap4-dialog#11]
Hello, I have a console error and the dialog doesn't shows with Bootstrap 4.3.1

> Uncaught TypeError: Cannot set property 'scrollTop' of null

Do you find it ?
Thanks

**Comment by Oviglo** [comment]
Oh sorry it's a bug with my code :/

**Comment by GedMarc** [comment]
will take a look

**Comment by GedMarc** [comment]
cool :)

**Comment by GedMarc** [comment]
will update the demos anyway tho, just in case
