### ISSUE TITLE
Get Some html constructions error with bootsrap 4.3

### ISSUE THREAD

**Issue by fklee** [GedMarc/bootstrap4-dialog#14]
Hi !,
Nice work with bootstrap 4 but I got some construction error with bootstrap 4.3. Error are in the header and in the footer where class have changed.

I will try to change this in a fork and create a pull request.

**Comment by GedMarc** [comment]
Ooo any chance of sharing what the errors are?

I did do an update to 4.3.1 but I may have missed something :)

Thanks!

**Comment by fklee** [comment]
Oh sorry, I didn't see this update, got the last version from NPM, noted as bootstrap4-dialog@4.1.0 how can i get version 4.3.1 ?

So I found these problems : 
- bad style for close button / default button
- little close (X) near the title is not positoned at right but just after the title.
- There is no space between buttons in footer

Hope I help you.

**Comment by xueyinghao** [comment]
Emmm，how can i get Version 4.3.1，I've seen the new release version is for 4.2. Under bootstrap 4.3 I get an error in the constructor like this;![image](https://user-images.githubusercontent.com/5610893/62929089-0790af00-bdba-11e9-9627-d642b3c415be.png).
Hope you can give me some help,thx

**Comment by GedMarc** [comment]
What are you pulling with? :)

**Comment by GedMarc** [comment]
@fklee Please check on the latest version --- The examples seem to be ok

![image](https://user-images.githubusercontent.com/5367513/63712668-70f2d200-c83e-11e9-91eb-f2917a9b59e3.png)

**Comment by fklee** [comment]
Thanks, I will try this ASAP !

**Comment by fklee** [comment]
Sorry for my late answer.
Why is latest version (4.3.1) not available on npm, I can found only version 4.1.0 from NPM ?

**Comment by GedMarc** [comment]
The original idea with this fork-off was to not deploy direct versions across, but to use git repo referencing instead. When this happened there was everything in the air with bower being discontinued, yarn coming into play, webpack magically got some people to use it, 
and between distributing across 456/7/8 repo's, I decided, rather just use the git pull directly.

It's worked well for everyone so far without adding any admin overhead to the project. There's also the hell-on-earth for npm to deploy under the same user over a period of time to a project which I have no time to entertain.

https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a

https://stackoverflow.com/questions/23210437/npm-install-private-github-repositories-by-dependency-in-package-json

This allows you to update at your leisure without being dependant on a 3rd party intermediary, registration or slow update, like npm.

In terms of adopting the policy to deploy to all the million repository managers - 
Remember there is also such a thing as repo-stealing ,so... no.

**Comment by fklee** [comment]
Hello,
Thanks for your long explanation, I just found how to add in package the direct address of the package. I never realized that I had th 4.1.0 not the 4.3.1 ! (as this was my really first question :-) )
I really don't know how to add a package to NPM repository.

Sorry and thanks for your support and portage to boostrap 4 of this great package for dialogs.

**Comment by GedMarc** [comment]
Sorry man! @fklee One of those downsides of aspergers lol, we tend to answer questions at length!

Glad it's working for you!
