### ISSUE TITLE
can't trigger javascript after BootstrapDialog.show({...}) page

### ISSUE THREAD

**Issue by HKChen** [GedMarc/bootstrap4-dialog#16]
I updated bootstrap 3 to 4.3.1 and bootstrap3-dialog to bootstrap4-dialog.
I use BootstrapDialog.show({... data: 'pageUrl' ...}) to open dialog work.
But in this dialog page can't trigger any javascript.

**Comment by GedMarc** [comment]
Please see https://github.com/GedMarc/bootstrap4-dialog/issues/15 

This is related to the change in the DOM loading with Bootstrap Modals. 
Instead of using onShow (Where the dom is not yet loaded), use onShown : function(){}; to fire when the DOM has finished being updated
