### ISSUE TITLE
On load remote page, not execute javascript

### ISSUE THREAD

**Issue by hugff** [GedMarc/bootstrap4-dialog#21]
Hi,

We are loading the modal's content using:

`
message: $('<div></div>').load('Sapp?/crmcustomer.newcrminput');
`

In load page, to try it, we have a simple javascript code like this one :
`

<script type="text/javascript"> 
     alert('inidlg'); 
</script> 

`

When we execute "BootstrapDialog.show" the dialog appears but this simple javascript doesn't work.

Thanks for this amazing tool.

**Comment by DimchoLakov** [comment]
Hi,

I can confirm that this problem exists. I am using ASP.NET Core and Visual Studio and when I load partial view into the dialog like this --> `message: $('<div></div>').load('/Home/Test/');`, the javascript code in the partial view is not executing.

**Comment by DimchoLakov** [comment]
Hi @hugff,

I encountered the same problem. Please take a look at this --> #15.

**Comment by GedMarc** [comment]
Is there any chance of attaching a quick example?
Mostly these items are https:// vs http:// calling, especially when crossing domain

Can you try :-
```
BootstrapDialog.show({
    message: $('<div></div>').load('remote.html'),
     onshown: function(){alert('displayed');}
});
```

**Comment by GedMarc** [comment]
```
BootstrapDialog.show({
    message: $('<div id="popupContent"></div>'),
    onshown: function () {
        $("#popupContent").load('remote.html')
    }
})
```

**Comment by DimchoLakov** [comment]
I found this approach by @shanu2rick  
`BootstrapDialog.show({
    message: $('<div id="popupContent"></div>'),
    onshown: function () {
        $("#popupContent").load('remote.html')
    }
})`

**Comment by hugff** [comment]
Ok Thanks,
This will be a good solution.
