### ISSUE TITLE
Close icon on right side

### ISSUE THREAD

**Issue by LocutusOfPenguin** [GedMarc/bootstrap4-dialog#23]
The close Icon is behind the title text (see also yr examples).
But it should be right aligned. To make this work i needed:

.bootstrap-dialog-header {
    width: 100%;
}

**Comment by GedMarc** [comment]
Awesome thanks for the heads up!

Will put this in on the next round of js library commits :)

**Comment by GedMarc** [comment]
Thanks included in the latest pull
