### ISSUE TITLE
NPM releases

### ISSUE THREAD

**Issue by tobz1000** [GedMarc/bootstrap4-dialog#25]
Hi,

The [latest version on NPM](https://www.npmjs.com/package/bootstrap4-dialog) is 4.1.0. Is it possible to update to the latest?

Otherwise, is there somewhere else I should point my package manifest to receive updates (preferably actual releases, rather than just master branch)?

**Comment by GedMarc** [comment]
Oh wow this one flew right past me

i'll see on sunday :)

**Comment by orwen89** [comment]
Hey! Any updates regarding this issue?

**Comment by GedMarc** [comment]
NPM isn't letting me login to perform an update, i may need a new account and a new coordinate :) Been a while since i've used npm

**Comment by GedMarc** [comment]
ok i've sorted out the login stuffs, lets see if i can update pretty easily

**Comment by GedMarc** [comment]
Ok so I think that did it - can you please confirm?

**Comment by GedMarc** [comment]
![image](https://user-images.githubusercontent.com/5367513/85542683-9ea0d700-b619-11ea-85ad-0318322c092e.png)

**Comment by tobz1000** [comment]
![image](https://user-images.githubusercontent.com/1471978/85543079-a492ba00-b611-11ea-9a62-8a3f697faefa.png)

The Versions tab still displays this for me. Does the new version need to be made public?

**Comment by GedMarc** [comment]
hmm shows public for me - 

let me logout and see

**Comment by GedMarc** [comment]
can you check here? maybe cntrl+f5

https://www.npmjs.com/search?q=bootstrap4-dialog

![image](https://user-images.githubusercontent.com/5367513/85543597-8087a680-b61a-11ea-8176-6b0de9e1ebb1.png)

**Comment by orwen89** [comment]
It shows 4.3.4 for me.
Thanks Marc for the update!

**Comment by tobz1000** [comment]
Yep, updating a project works. I guess that page is cached for my IP or something. Thanks!
