### ISSUE TITLE
Backdrop not Closed when Closing Dialog with Bootstrap 4.5.1

### ISSUE THREAD

**Issue by jogibear9988** [GedMarc/bootstrap4-dialog#27]
When I Update to Bootstrap 4.5.1 and open a Dilaog and Close it with clicking on the Backdrop,
the backdrop stays open.

With 4.5.0 it works

**Comment by jogibear9988** [comment]
https://github.com/twbs/bootstrap/issues/31622

**Comment by jogibear9988** [comment]
see http://jsfiddle.net/qu6r3shn/1/

**Comment by GedMarc** [comment]
Ok so updating the 4.5.2 seems to fix it -

Please check the latest on the branch, and with that bootstrap (and popper/tether versions) all dialogs use the backdrop :) 
4.5.1 looks like that bugged out right now

**Comment by GedMarc** [comment]
bootstrap4-dev branch :)

**Comment by jogibear9988** [comment]
No 4.5.2 does also not work.
Bootstrap Dev I've not tested.

Try 4.5.2 in the JsFiddle... it does not work

**Comment by GedMarc** [comment]
workaround for now while i try find the root cause
animate : false

```
BootstrapDialog.show({
	title: 'Example',
    message: 'Write your example here.',
    animate:false,
    buttons: [{
   		label: 'Close',
        action: function(dialog) {
        	dialog.close();
        }
    }]
});
```

**Comment by GedMarc** [comment]
ok

the version on cdn.jsdelivr.net hasn't updated, the current version is fine so shew! There was an update before to use bootstrap modal close instead, looks like that hasn't filtered through there-

Now to investigate how jsdelivr work sigh

**Comment by jogibear9988** [comment]
thanks.

kann you also look at my pull req about the readme?

**Comment by GedMarc** [comment]
Thanks for the report!

http://jsfiddle.net/okyhrgnq/1/
