### ISSUE TITLE
Opening multiple dialogs ERROR

### ISSUE THREAD

**Issue by rcarhuaricra** [GedMarc/bootstrap4-dialog#33]
cuando utilizo la opcion de multiples modales, e intento cerrar el primero se pierde la barra de deslizamiento

**Comment by GedMarc** [comment]
english please :)

**Comment by GedMarc** [comment]
necesitan mucha más información que eso

**Comment by rcarhuaricra** [comment]
lo solucione agregando este script:
*************************************************************
           let openedDialogs = $(".modal.bootstrap-dialog.show");
            if (openedDialogs.length > 0) {
                setTimeout(function(){
                    let openedDial = $(".modal.bootstrap-dialog.show");
                    if (openedDial.length > 0) {
                        $("body").addClass('modal-open');
                    }
                }, 380)
            }
*************************************************************
en la linea 1225 del archivo **bootstrap-dialog.js** despues de:
**this.getModal().modal('hide');**
el modal tarda en cerrarse 300 lo que tardara en quitar la class **modal-open** calculamos si aun existe algun modal activo y agregamos nueva mente la class  **modal-open** 

espero les sirva saludos

**Comment by GedMarc** [comment]
Primero tenemos que asegurarnos de que hay un problema - No puedo parecer replicar ningún problema en el ejemplo de demostración - ¿Puede enviar a través de un replicador

**Comment by GedMarc** [comment]
.......

**Comment by GedMarc** [comment]
No replicator

**Comment by rcarhuaricra** [comment]
http://jsfiddle.net/cuq4zt13/

**Comment by rcarhuaricra** [comment]
changes cannot be seen from NPM

**Comment by GedMarc** [comment]
https://www.npmjs.com/package/bootstrap4-dialog

**Comment by GedMarc** [comment]
sorted?
