### ISSUE TITLE
(Cosmetic issue) Buttons are stuck to each other with no spacing

### ISSUE THREAD

**Issue by melvinchia** [GedMarc/bootstrap4-dialog#4]
![image](https://user-images.githubusercontent.com/2408261/42366377-99d3608e-8133-11e8-96bd-b4cf99f0c21d.png)

Problem:
bootstrap-dialog-footer-buttons are stuck to each other with no spacing (See screenshot above)

Solution:
`.bootstrap-dialog-footer-buttons > .btn { margin-left: 10px; }`

![image](https://user-images.githubusercontent.com/2408261/42366409-b02db51e-8133-11e8-991c-87ebfe066ee1.png)

**Comment by GedMarc** [comment]
Would it be better to apply a sink to the buttons instead of a strictly typed number?
I know a few projects where the margins altered and the set figure may disrupt that a bit?

Would this work?
```
class="ml-1"
```

**Comment by melvinchia** [comment]
Right. I got it to work by adding the class, and no additional CSS.
