### ISSUE TITLE
Not working with bootstrap 5

### ISSUE THREAD

**Issue by SwetaBansall** [GedMarc/bootstrap4-dialog#41]
I have used this library this is working with bootstrap 4 but when I use bootstrap 5 it shows below console error on page load and also when popup button is clicked. Popup does not open. 

![image](https://user-images.githubusercontent.com/105705898/168759236-dff182b4-d5db-4bdf-9ce7-6b60be73965f.png)

In the code sample when bootstrap 5 CDN is used instead of 4 then there also popup is not visible.
http://jsfiddle.net/qu6r3shn/

**Comment by GedMarc** [comment]
The CDN JS version referred to in the fiddle is not the latest, which does work with v5 - it's very outdated.

**Comment by GedMarc** [comment]
Use - https://cdn.jsdelivr.net/gh/GedMarc/bootstrap4-dialog@bootstrap4-dev/dist/js/bootstrap-dialog.js instead

**Comment by GedMarc** [comment]
JSDelivr does not recommend using a non-specified branch or version as per their landing page ;) 

https://www.jsdelivr.com/

**Comment by SwetaBansall** [comment]
Thank you for reply. 
I was using same JavaScript and CSS file. I took it from "dist" folder from the code.
I am using jquery-3.6.0 and bootstrap-5.0.2 and bootstrap-datepicker-1.6.0 and JS and CSS from dist folder (your code) and in same sequence.

**Comment by GedMarc** [comment]
please create a fiddle with your requirements, it will definitely be something with your structure

**Comment by GedMarc** [comment]
(y)

**Comment by SwetaBansall** [comment]
Thank you so much. Now its working

**Comment by rcarhuaricra** [comment]
I'm trying to call it via npm but it doesn't work

**Comment by rcarhuaricra** [comment]
![image](https://user-images.githubusercontent.com/19846753/179391850-02a19a70-f08b-449b-af00-f22181d71e96.png)

**Comment by GedMarc** [comment]
Hmm with 5.0.1 not being compatible we have to set each individually - not possible to bump to 5.2?
Will see if there's a cleaner way to version identify
