### ISSUE TITLE
outdated npm

### ISSUE THREAD

**Issue by rcarhuaricra** [GedMarc/bootstrap4-dialog#43]
Hello, I am trying to work with bootstrap version 5.1.3 through NPM but I see that the latest version is not on par with this one, could you update it please.
sorry to bother about the same thing every year #33

**Comment by GedMarc** [comment]
what cdn are you using? the versions isn't typed for this?

**Comment by GedMarc** [comment]
4.2.2 is the latest?

**Comment by rcarhuaricra** [comment]
> what cdn are you using? the versions isn't typed for this?

estoy usando sin ningun cdn

**Comment by rcarhuaricra** [comment]
> 4.2.2 is the latest?

in the version that appears in npm it is 4.2.2 that is not compatible with bootstrap 5

**Comment by rcarhuaricra** [comment]
https://www.npmjs.com/package/bootstrap4-dialog 
4.2.2

**Comment by GedMarc** [comment]
4.4.3 :)
