### ISSUE TITLE
bye bye jquery

### ISSUE THREAD

**Issue by rcarhuaricra** [GedMarc/bootstrap4-dialog#48]
at some point will we stop using jQuery? I would like to integrate the library with svelte or react without including jQuery

**Comment by GedMarc** [comment]
I guess when I choose to break all backwards compatibility to bootstrap 4 and 3, might have quite a bit of kick-back doing that honestly, the main point of this library is to assist with a modal service type structure for modal presentation that is portable through bootstrap versions...

But - you don't need this library for modals on a typescript stage for bootstrap 5 and up, regardless of the implementation, and I don't have any plans for making schema definitions or migrating to typescript for this library (again it's really not needed on the new stuff)

Aside from the modal implementation of bootstrap having finally matured properly, the implementation of a modal service regardless of platform (2way angular or 1way react or or or) is not really worthy of a full support API -  it would add more complexity than the out of the box solution, JSX and the likes are doing all this for you - 
it's a better option to do a simple google, grab the typescript modal service that meets your requirements and target es version, and go from there 

If you really want to make your own modal service, get very comfortable with the module format of the bootstrap JS framework, and the biggest decision you'll need to make is to trigger modals on a navigation route, and/or to trigger them through events, which will be a platform dependent implementation 

https://getbootstrap.com/docs/5.2/getting-started/javascript/
https://getbootstrap.com/docs/5.2/components/modal/#via-javascript

**Comment by GedMarc** [comment]
To be clear - it is not recommended to use this library in a managed typescript framwork, as it does not interoperate or cater for  any form of shadow dom
