### ISSUE TITLE
Error in determining version

### ISSUE THREAD

**Issue by maverickbluer1** [GedMarc/bootstrap4-dialog#51]
![bootstrap4-dialog-error](https://user-images.githubusercontent.com/4293089/210839298-c21357d1-dbc7-41f7-a5cb-8266c21772b9.png)

I'm getting an error I can't resolve pictured in the attached image.  The error is in line 55.

I'm using BootStrap 5.1.0.  I have tried other versions including rolling back to 4.x with no joy.  Could you help me?

Thanks!

Pat

**Comment by pslmr** [comment]
> ![bootstrap4-dialog-error](https://user-images.githubusercontent.com/4293089/210839298-c21357d1-dbc7-41f7-a5cb-8266c21772b9.png)
> 
> I'm getting an error I can't resolve pictured in the attached image. The error is in line 55.
> 
> I'm using BootStrap 5.1.0. I have tried other versions including rolling back to 4.x with no joy. Could you help me?
> 
> Thanks!
> 
> Pat

where you able to fix this??

**Comment by maverickbluer1** [comment]
I'm sorry but I don't remember what I did to fix it

**Comment by GedMarc** [comment]
The code on the screen shot isn't representative of an actual build in the past ... 2 years?
Are you using a CDN? can you check that you are indeed running the latest ver?

<img width="619" alt="image" src="https://user-images.githubusercontent.com/5367513/236288725-5b74abd0-3f61-4ba2-9f59-da93285f9d50.png">
