### ISSUE TITLE
Bootstrap 5.2.3/5.3.2 Support

### ISSUE THREAD

**Issue by awilson69** [GedMarc/bootstrap4-dialog#52]
Are you planning to support newer versions of Bootstrap.  Using the latest version of Bootstrap-Dialog, v4.4.4, I am unable to open an instance of the dialog anymore.  

Using the following basic code example with either Bootstrap v5.2.3 or v5.3.2, I get the error further below:

Code Example 
            BootstrapDialog.show({
                size: BootstrapDialog.SIZE_WIDE,
                title: "Loading Customer Request",
                message: `<br/>Customer Request search page is being loaded.  Please wait . . .`,
                type: "type-info",
                closeByBackdrop: false,
                closeByKeyboard: false,
                closable: true,
                draggable: true,
            })

Console Error
bootstrap-dialog.min.js:1  Uncaught TypeError: Class constructor On cannot be invoked without 'new'
    at new BootstrapDialogModal (bootstrap-dialog.min.js:1:695)
    at BootstrapDialog.realize (bootstrap-dialog.min.js:1:25348)
    at BootstrapDialog.open (bootstrap-dialog.min.js:1:8047)
    at BootstrapDialog.show (bootstrap-dialog.min.js:1:26338)
    at CustomerLanding.aspx:1125:29
    at dispatch (jquery.min.js:2:43090)
    at v.handle (jquery.min.js:2:41074)

**Comment by GedMarc** [comment]
This seems like you are using the wrong version of the library

**Comment by awilson69** [comment]
It was a problem on my end that I found/fixed.  All seems to be well now.  Thank you for getting back to me.  I love this library!!

**Comment by awilson69** [comment]
It was a problem on a my end that I found/fixed.  Thank you for getting back to me.
