### ISSUE TITLE
Buttons in SIZE_WIDE are pushed to new lines

### ISSUE THREAD

**Issue by jarodhanko** [GedMarc/bootstrap4-dialog#6]
bootstrap-dialog.js 
line 232

//btn block makes buttons display: 'block' 
BootstrapDialog.BUTTON_SIZES[BootstrapDialog.SIZE_WIDE] = 'btn-block'; 

What is the intended behavior here?  Also, there is no class added to SIZE_EXTRAWIDE.

I suggest not basing the button sizes on the modal width, at least by default, since it is already possible to pass classes if you create the buttons manually.

Let me know if you want an example (although i can't do a jsfiddle until you update npm).

**Comment by GedMarc** [comment]
1. What is the intended behavior here? Also, there is no class added to SIZE_EXTRAWIDE.

Applying the bootstrap classes allows to add the buttons uniformly via JS, it's part of the original plugin and works quite well - A decent shortcut - If you look at the bottom of the examples page you can see how it maps the BOOTSTRAP_TYPES

SIZE_EXTRAWIDE is applied through a 90% width style in CSS .modal-xl - No bootstrap equivalent exists for this.
Line 605 :
```
 // Extra Wide Dialog.
                this.getModalDialog().removeClass('modal-xl');
                if (this.getSize() === BootstrapDialog.SIZE_EXTRAWIDE) {
                    this.getModalDialog().addClass('modal-xl');
                }
```

I'm struggling doing a release on Github - not liking pushing the perform a release button - logged a support ticket, I see they've replied saying its sorted, was gonna get to it today :)

**Comment by jarodhanko** [comment]
I am not sure I am completely following you, but run the following code (after updating bootstrap-dialog references).  

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.css" rel="stylesheet"/>
  <link href="./bootstrap-dialog.css" rel="stylesheet"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/js/bootstrap.js"></script>
  <script src="./bootstrap-dialog.js"></script>
  
</head>
<body>
  <button type="button" class="btn btn-default" onclick="BootstrapDialog.show({
            message: 'Hi Apple!',
			size: BootstrapDialog.SIZE_WIDE,
            buttons: [{
                label: 'Button 1',
                title: 'Mouse over Button 1'
            }, {
                label: 'Button 2',
                // no title as it is optional
                cssClass: 'btn-primary',
                data: {
                    js: 'btn-confirm',
                    'user-id': '3'
                },
                action: function(){
                    alert('Hi Orange!');
                }
            }, {
                icon: 'glyphicon glyphicon-ban-circle',
                label: 'Button 3',
                title: 'Mouse over Button 3',
                cssClass: 'btn-warning'
            }, {
                label: 'Close',
                action: function(dialogItself){
                    dialogItself.close();
                }
            }]
        });">
    Click to open dialog
  </button>
  
  
  
</body>
</html>
```

**Comment by GedMarc** [comment]
can you post it as a zip? didn't come out right i think

**Comment by jarodhanko** [comment]
[Demo.zip](https://github.com/GedMarc/bootstrap4-dialog/files/2452253/Demo.zip)

**Comment by GedMarc** [comment]
Looks like the release went through successfully, 

Added display:flex to the footer buttons div.

If  happy please close :) Thanks!

**Comment by GedMarc** [comment]
I'm wondering if its not doing this just because of the btn-block in which case it is correct... /

**Comment by jarodhanko** [comment]
Yes without the btn-block that does not happen.  I haven't had a chance to test your fix yet.

**Comment by GedMarc** [comment]
it has a positioning bug on the first button

**Comment by GedMarc** [comment]
If you can please have a look at the latest commit,
I think that's pretty close to sorted.

**Comment by jarodhanko** [comment]
Looks good!

**Comment by jarodhanko** [comment]
It is a little weird that only SIZE_WIDE has buttons that take up all the visible space (flex) from a consistency standpoint, but it will work for me.

**Comment by GedMarc** [comment]
it is very weird, has to do with the new flex grid system :)
