### ISSUE TITLE
README install instructions still name bootstrap3-dialog

### ISSUE THREAD

**Issue by rhys-vdw** [GedMarc/bootstrap4-dialog#7]
Hey, mainly wanted to create an issue to thank you for the package @GedMarc. Seems to be working as a drop-in replacement for bootstrap3-dialog after upgrading bootstrap4.

However, README still mentions the old package, and also your listing in bower has the wrong repo link:

![image](https://user-images.githubusercontent.com/822105/46924345-92582e80-d06f-11e8-8fc1-4705ca5b9cb9.png)

**Comment by rhys-vdw** [comment]
Actually that's not even this package on Bower. Quite confusing.

**Comment by GedMarc** [comment]
Hmm I try to keep it as much as possible, I did update the bower information, the bower that I use is 
```
  "dependencies": {
    "bootstrap4-dialog": "https://github.com/GedMarc/bootstrap-dialog.git#*"
  }
```

Hmm yes I see... No I don't believe this is published in bower
