### ISSUE TITLE
e.querySelector is not a function

### ISSUE THREAD

**Issue by micronax** [GedMarc/bootstrap4-dialog#8]
I encountered the follow error while using `BootstrapDialog.confirm()` with Bootstrap 4.1.3:

`Uncaught TypeError: e.querySelector is not a function`

Tracing down the changes between boostrap 4.0 and 4.1.3 I got the following:

![bildschirmfoto 2018-11-22 um 11 55 52](https://user-images.githubusercontent.com/1337823/48898649-938a3180-ee4d-11e8-8319-229e0653f074.png)

in `bootstrap/js/src/modal.js` in the current 4.1.3 package.

**Comment by GedMarc** [comment]
Hmm this is interesting! It should be good for bootstrap 4.1.1 (my last test), I'll update the bootstrap version and go through those changes!

Thanks for letting me know! - I wonder if the change will be backwards with 4.1.1

**Comment by micronax** [comment]
Seems like they changed it in v4.1.2:

https://github.com/twbs/bootstrap/commit/a79b8aa16ab5fa5c71a91425d8464f0bdcd3fe37#diff-654bf5561940258164848136667836eaL81

**Comment by GedMarc** [comment]
Yep, in the changelog...
Improved how we query elements in our JavaScript plugins

I'll get this done now, probably have to create another version break.. ;/

**Comment by GedMarc** [comment]
hmm browser? can't seem to replicate - version of jquery you are using?

**Comment by GedMarc** [comment]
i'll post the index and js updates, in the demo there is a confirm at the bottom that i'm testing with

**Comment by GedMarc** [comment]
#14a0856

**Comment by GedMarc** [comment]
https://github.com/GedMarc/bootstrap4-dialog/commit/14a08560bad514c18eff462f464f7a9976a20aca

**Comment by GedMarc** [comment]
Please confirm that the example with bootstrap 4.1.3 is working, closing with no response this evening

**Comment by GedMarc** [comment]
Closing - No Response
