### ISSUE TITLE
sass for bootstrap theme colors

### ISSUE THREAD

**Issue by njake** [GedMarc/bootstrap4-dialog#9]
`sass`
.bootstrap-dialog {
    @each $color, $value in $theme-colors {
      &.type-#{$color} {
         .modal-header {
            background-color: $value;
        }
      }
    }
    
    .bootstrap-dialog-header{
        flex: auto;
        .bootstrap-dialog-title {
            color: #fff;
            font-size: 16px;
        }
    
        .bootstrap-dialog-close-button {
            float: right;
        }
    
        .bootstrap-dialog-close-button button {
            opacity: 0.9;
            &:hover {
                color: #fff;
                opacity: 1;
            }            
        }
    }
}

**Comment by GedMarc** [comment]
Hi @njake,

This project uses LESS, not SASS :)

What would be the goal of this? the only thing I can see happening different here is application of opacity?

**Comment by njake** [comment]
Bootstrap uses sass and i wanted to share how to play with same tool.

Goal is loop all theme-colors and make diffirent dialog color variants without spesifying them manually.
Users can add theme-colors in new bootstrap and sass each loop make them all.

Current code that i use
`
.bootstrap-dialog {
    @each $color, $value in $theme-colors {
      &.type-#{$color} {
         .modal-header {
            background-color: $value;
        }
      }
    }
    
    .bootstrap-dialog-header{
        display: flex;
        width: 100%;
        .bootstrap-dialog-title {
            margin-right: auto !important;
            color: #fff;
            font-size: 16px;
        }
    
        .bootstrap-dialog-close-button button {
            opacity: 0.9;
            &:hover {
                color: #fff;
                opacity: 1;
            }            
        }
    }
    
    .bootstrap-dialog-button-icon {
        margin-right: 10px;
    }    
}
`

**Comment by GedMarc** [comment]
Let me see if I can give this another look

**Comment by GedMarc** [comment]
Ref https://github.com/GedMarc/bootstrap4-dialog/pull/20 :)
